---
packages:
  - core/api
  - apps/consent
  - apps/dashboard
  - apps/admin-panel
  - apps/pay
  - apps/map
  - apps/voucher
  - apps/shopify-blink
  - apps/shopify-blink/extensions/checkout-ui
  - bats/helpers/callback
  - bats/helpers/subscriber
  - bats/helpers/totp
  - lib/eslint-config
  - lib/gt3-server-node-express-sdk
  - lib/galoy-components
